import { ThemeProvider } from "@/components/ui/theme-provider";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "@/components/common/Navbar";
import Provider from "@/components/common/Provider";
import { TailwindIndicator } from "@/components/common/tailwindIndicator";
import ModalProvider from "@/provider/previewModalProvider";
import { Toaster } from "@/components/ui/toaster"
import PreviewModal from "@/components/browse/PreviewModal";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
})
{
  return (
    <html lang="en">
      <body className={inter.className + " debug-screens"}>
        <Provider>
          <PreviewModal />
          {/* <ModalProvider /> */}
          <Toaster />
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            {children}
          </ThemeProvider>
        </Provider>
        <TailwindIndicator />
      </body>
    </html>
  );
}
